#!/bin/bash
# Sets up a working environment with CMake
if [[ "$(ls -A)" ]]; then
    read -r -p 'Directory not empty. Proceed? (y/n)' yn
    if [[ "$yn" != 'y' ]]; then
        exit 1
    fi
fi

mkdir build
mkdir src

if [[ "$(pwd)" =~ ^.+/([^/]+)$ ]]; then
    proj="${BASH_REMATCH[1]}"
fi

cat << EOM > CMakeLists.txt
cmake_minimum_required(VERSION 3.22)	# Used by CSIF
project(
    ${proj}
    VERSION 1.0
    DESCRIPTION "description"			# TODO
    LANGUAGE CXX
    )

# For YouCompleteMe
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable(executable)			# TODO
target_sources(executable PRIVATE source)	# TODO
EOM

git init
