#!/bin/bash
# csif [-t] [-c computer_num]
# Connect to school computers
# 	Modes: 'c'ontrol computer, 't'ransfer files

computer_num=32
transfer_mode=0
while getopts "tc:" opt; do
    case $opt in
	t)
	    transfer_mode=1
	    ;;
	c)
	    computer_num=$OPTARG
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    ;;
    esac
done

if [[ "$transfer_mode" == 1 ]]; then
    sftp xydxydxy@pc"$computer_num".cs.ucdavis.edu
else
    ssh xydxydxy@pc"$computer_num".cs.ucdavis.edu
fi
