#!/bin/bash
# ezmerge
# push branch, merge with main, and delete branch

if [[ "$#" -ge 1 ]]; then
    echo "Usage: quickmerge" >&2
    exit 1
fi

fix_branch="$(git rev-parse --abbrev-ref HEAD)"
read -r -p "On branch $fix_branch, proceed? " yn
if [[ "$yn" != 'y' ]]; then
	exit 1
fi

firstpush
xdg-open "$(git config remote.origin.url)"

yn='n'
while [[ "$yn" != 'y' ]]; do
	read -r -p 'Merged? ' yn
done

git checkout main
git pull

read -r -p "Delete $fix_branch? " yn
if [[ "$yn" != 'y' ]]; then
	exit 0
fi
git branch -d "$fix_branch"
