#!/bin/bash
# newsh scriptname arg1 arg2 ...
# set up a new shellscript
if [[ "$#" -lt 1 ]]; then
    echo "Illegal number of parameters" >&2
    exit 1
fi

filename=$1
if test -f $filename; then
    echo "$filename already exists" >&2
    exit 2
fi

shift 1
args=("$@")

# Shellscript template
cat << EOM > "$filename"
#!/bin/bash
# ${filename} ${args[*]}
#
if [[ "\$#" -ne ${#args[@]} ]]; then
    echo "Illegal number of parameters" >&2
    exit 1
fi
while getopts "d" opt; do
    case \$opt in
	d)
	    unset GTEST_FILTER
	    exit 0;
	    ;;
	\?)
	    echo "Invalid option: -\$OPTARG" >&2
	    ;;
    esac
done
EOM

# Setup the rest
chmod +x "$filename"
nvim "$filename"
