#!/bin/bash
# run [-x language] [-g] srcfile
# quickly build and run file
# Supported language: cxx (default), asm

while getopts "x:g" opt; do
    case $opt in
	x)
	    lang="$OPTARG"
	    shift 2;
	    ;;
	g)
	    debug=1
	    shift 1;
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    exit 1
	    ;;
    esac
done

# check for safe environment
if [[ -f temp.o || -f temp.out ]]; then
    read -r -p "temp may be deleted. Proceed? (y/n)" yn
    if [[ "$yn" !=  y ]]; then
	echo "Aborting..."
        exit 1
    fi
fi

# CXX
if [[ "$lang" == '' || "$lang" == 'cxx' ]]; then
    if [[ "$debug" ]]; then
	$CXX "$1" -g $CXXFLAGS
	shift 1
	gdb -tui a.out
    else
	$CXX "$1" $CXXFLAGS
	shift 1
	./a.out "$@"
    fi
    rm -rf a.out a.out.dSYM
# ASM
elif [[ "$lang" == "asm" ]]; then
    echo "Assembling $1..."
    as --gstabs --32 -o "temp.o" "$1"
    ld -melf_i386 -o "temp.out" "temp.o"

    echo "Running temp.out"
    gdb -tui -ex "b done" "temp.out"
    rm -rf "temp.out" "temp.o"
fi
